package in.co.rays.model;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import in.co.rays.bean.UserBean;
import in.co.rays.util.JDBCDataSource;

public class UserModel {

	public void add(UserBean bean) throws Exception {
		//Class.forName("com.mysql.cj.jdbc.Driver");
		//Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/advance_java","root","root");
		
	
		Connection cn = JDBCDataSource.getConnection();
		PreparedStatement ps = cn.prepareStatement("insert into user values(?,?,?,?,?,?,?)");
		ps.setInt(1, bean.getId());
		ps.setString(2, bean.getFirstName());
		ps.setString(3, bean.getLastName());
		ps.setString(4, bean.getLoginId());
		ps.setString(5, bean.getPassword());
		ps.setDate(6, new java.sql.Date(bean.getDob().getTime()));
		ps.setString(7, bean.getAddress());
		
		int i = ps.executeUpdate();
		System.out.println("Data inserted ="+i);
		
		
	}
}
